#I-Free
com:
  ifree:
    amqp:
      enabled: true
      exchange: async.task.test.queue
      routing-key: async.task.test.queue
      host: amqp://srv7-dasar
      port: 5672
      username: guest
      password: guest
      virtual-host: /

logging.level:
  root: INFO

#Spring
spring:
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver